name = "glyph-theme"

[appearance]
bg = "#1b1d23"
fg = "#c8c093"

[gutter]
bg = "#2c2e34"
fg = "#7e7e7e"

[statusline]
inner = { fg = "#cecece", bg = "#3c3e44" }

[tokens]
function = { fg = "#7daea3" }
"function.method" = { fg = "#82aaff" }
"function.macro" = { fg = "#ff9e64" }
"constant.builtin" = { fg = "#ffcc66" }
constant = { fg = "#d8a657" }
type = { fg = "#569CD6" }
"type.builtin" = { fg = "#4EC9B0" }
constructor = { fg = "#B5CEA8" }
property = { fg = "#CE9178" }
"variable.parameter" = { fg = "#9CDCFE" }
"variable.builtin" = { fg = "#C586C0" }
label = { fg = "#D7BA7D" }
comment = { fg = "#608B4E" }
"punctuation.bracket" = { fg = "#D4D4D4" }
"punctuation.delimiter" = { fg = "#D4D4D4" }
keyword = { fg = "#C586C0" }
string = { fg = "#CE9178" }
escape = { fg = "#d7ba7d" }
operator = { fg = "#569CD6" }
attribute = { fg = "#4EC9B0" }
