theme = ""
mouse_scroll_lines = 3
gutter_width = 6
line_numbers = "Absolute"
background = "Dark"
empty_line_char = "~"
show_diagnostics = true

[keys.normal]
"x" = "DeleteCurrentChar"
"w" = "NextWord"
"o" = ["InsertLineBelow", { EnterMode = "Insert" }]
"u" = "Undo"
"z" = { "z" = "CenterLine" }
":" = { EnterMode = "Command" }
"g" = { "g" = "MoveToTop", "d" = "GoToDefinition" } 
"I" = ["MoveToLineStart", { EnterMode = "Insert" }]
"End" = "MoveToLineEnd"
"Home" = "MoveToLineStart"
"n" = "FindNext"
"Right" = "MoveRight"
"p" = "PasteBelow"
"O" = ["InsertLine", { EnterMode = "Insert" }]
"k" = "MoveUp"
"l" = "MoveRight"
"/" = { EnterMode = "Search" }
"Down" = "MoveDown"
"Up" = "MoveUp"
"S-g" = "MoveToBottom"
"C-d" = "PageDown"
"C-u" = "PageUp"
"b" = "PreviousWord"
"a" = [{ EnterMode = "Insert" }, "MoveRight"]
"$" = "MoveToLineEnd"
"i" = { EnterMode = "Insert" }
"S-a" = [{ EnterMode = "Insert" }, "MoveToLineEnd"]
"d" = { "w" = "DeleteWord", "d" = "DeleteLine", "b" = "DeleteBack" }
"0" = "MoveToLineStart"
"Left" = "MoveLeft"
"S-n" = "FindPrevious"
"j" = "MoveDown"
"h" = "MoveLeft"

[keys.insert]
"Esc" = { EnterMode = "Normal" }
"C-c" = { EnterMode = "Normal" }
"Backspace" = "DeletePreviousChar"
"Tab" = "InsertTab"
"Enter" = "InsertLine"
"j" = { "k" = { EnterMode = "Normal" }}

[keys.command]
"Esc" = { EnterMode = "Normal" }
"C-c" = { EnterMode = "Normal" }
