theme = ""
mouse_scroll_lines = 3
gutter_width = 6
line_numbers = "Absolute"
background = "Dark"
empty_line_char = "~"
show_diagnostics = true

[keys.normal.z.Complex.z]
Simple = "CenterLine"

[keys.normal.x]
Simple = "DeleteCurrentChar"

[keys.normal.w]
Simple = "NextWord"

[keys.normal.o]
Multiple = ["InsertLineBelow", { EnterMode = "Insert" }]

[keys.normal.u]
Simple = "Undo"

[keys.normal.":".Simple]
EnterMode = "Command"

[keys.normal.g.Complex.d]
Simple = "GoToDefinition"

[keys.normal.g.Complex.g]
Simple = "MoveToTop"

[keys.normal.I]
Multiple = ["MoveToLineStart", { EnterMode = "Insert" }]

[keys.normal.End]
Simple = "MoveToLineEnd"

[keys.normal.Home]
Simple = "MoveToLineStart"

[keys.normal.n]
Simple = "FindNext"

[keys.normal.Right]
Simple = "MoveRight"

[keys.normal.p]
Simple = "PasteBelow"

[keys.normal.O]
Multiple = ["InsertLine", { EnterMode = "Insert" }]

[keys.normal.k]
Simple = "MoveUp"

[keys.normal.l]
Simple = "MoveRight"

[keys.normal."/".Simple]
EnterMode = "Search"

[keys.normal.Down]
Simple = "MoveDown"

[keys.normal.Up]
Simple = "MoveUp"

[keys.normal.G]
Simple = "MoveToBottom"

[keys.normal.C-d]
Simple = "PageDown"

[keys.normal.C-u]
Simple = "PageUp"

[keys.normal.b]
Simple = "PreviousWord"

[keys.normal.a]
Multiple = [{ EnterMode = "Insert" }, "MoveRight"]

[keys.normal."$"]
Simple = "MoveToLineEnd"

[keys.normal.i.Simple]
EnterMode = "Insert"

[keys.normal.A]
Multiple = [{ EnterMode = "Insert" }, "MoveToLineEnd"]

[keys.normal.d.Complex.w]
Simple = "DeleteWord"

[keys.normal.d.Complex.d]
Simple = "DeleteLine"

[keys.normal.d.Complex.b]
Simple = "DeleteBack"

[keys.normal.q]
Simple = "Quit"

[keys.normal.0]
Simple = "MoveToLineStart"

[keys.normal.Left]
Simple = "MoveLeft"

[keys.normal.N]
Simple = "FindPrevious"

[keys.normal.j]
Simple = "MoveDown"

[keys.normal.h]
Simple = "MoveLeft"

[keys.insert.Caps.Simple]
EnterMode = "Normal"

[keys.insert.Backspace]
Simple = "DeletePreviousChar"

[keys.insert.Tab]
Simple = "InsertTab"

[keys.insert.Enter]
Simple = "InsertLine"

[keys.insert.j.Complex.k.Simple]
EnterMode = "Normal"

[keys.insert.Esc.Simple]
EnterMode = "Normal"

[keys.command.Esc.Simple]
EnterMode = "Normal"

[keys.command.C-c.Simple]
EnterMode = "Normal"
