name: coverage

on: [push]
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo tarpaulin --all-features --workspace -o lcov --output-dir coverage --engine llvm

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
